//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class TestHelperWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("TestHelper");
		L.RegFunction("GetNetworkController", GetNetworkController);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetNetworkController(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			Protocols.NetworkController o = TestHelper.GetNetworkController();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

