/********************************************************************
	filename: 	CommonPlatform\Server\ServerInstance\Protocols\ProtoID.cs
	file base:	ProtoID.xml
	file ext:	cs
	author:	    刘祎
	
	purpose:    Client实例协议定义
    NOTE:       此文件为T4模板生成,请不要人工修改! 
                THIS　FILE IS GENERATED BY T4 TEMPLATE, MANUAL UPDATE IS NOT ALLOWED!
*********************************************************************/
using System;

namespace Protocols
{

	/// <summary>
    /// 通用协议定义体.
    /// 部分类,见 Prefab/ProtoIDPrefab.cs 
    /// </summary>
    public partial class ProtoID
    {
    }
}