--[[********************************************************************
	filename: 	CommonPlatform\Server\ServerInstance\Protocols\ProtoID.lua
	file base:	ProtoID.xml
	file ext:	lua
	author:	    黄帅
	
	purpose:    Client协议号定义-Lua版本
    NOTE:       此文件为T4模板生成,请不要人工修改! 
                THIS　FILE IS GENERATED BY T4 TEMPLATE, MANUAL UPDATE IS NOT ALLOWED!
*********************************************************************]]

Protocal = {
	Connect		= '101';	--连接服务器
	Exception   = '102';	--异常掉线
	Disconnect  = '103';	--正常断线   
	Message		= '104';	--接收消息
    CMD_LUA_EVENT = 406;
    CMD_LUA_EVENT_CALLBACK = 407;

}